import streamlit as st
import pandas as pd
import os
import time
from PIL import Image

# Import the main forecasting script
# We will call its main() function when the user clicks the button
import MAT_case_Study as forecast_model

# --- Page Configuration ---
st.set_page_config(
    page_title="Demand Forecasting Dashboard",
    page_icon="📈",
    layout="wide"
)

# --- File Definitions ---
DESIGN_DOC_FILE = 'Forecasting_Design_Doc.md'
VALIDATION_RESULTS_CSV = 'validation_overall_model_comparison.csv'
FORECAST_CSV = 'demand_forecast_best_model_next_6_months.csv'
PLAN_CSV = 'production_plan_best_model_next_6_months.csv'
PLOT_DIR = 'validation_plots'

# --- Helper Function to Load & Cache Files ---
@st.cache_data
def load_data(file_path):
    if not os.path.exists(file_path):
        return None
    if file_path.endswith('.csv'):
        return pd.read_csv(file_path)
    elif file_path.endswith('.md'):
        with open(file_path, 'r') as f:
            return f.read()
    return None

@st.cache_data
def load_image(image_path):
    if not os.path.exists(image_path):
        return None
    return Image.open(image_path)

# --- Main App ---
st.title("📈 SKU-Level Demand Forecasting & Production Planning")
st.markdown("A dashboard to present the model methodology, run the forecast, and analyze the results.")

# --- Create Tabs ---
tab_overview, tab_run, tab_results = st.tabs([
    "Project Overview", 
    "Run Forecast Pipeline", 
    "View Results"
])

# --- Tab 1: Project Overview ---
with tab_overview:
    st.header("Project Design & Methodology")
    markdown_content = load_data(DESIGN_DOC_FILE)
    if markdown_content:
        st.markdown(markdown_content, unsafe_allow_html=True)
        st.download_button(
            label="Download Design Doc (.md)",
            data=markdown_content,
            file_name=DESIGN_DOC_FILE,
            mime='text/markdown',
        )
    else:
        st.error(f"Error: `{DESIGN_DOC_FILE}` not found. Please make sure it's in the same directory.")

# --- Tab 2: Run Forecast Pipeline ---
with tab_run:
    st.header("Run the 5-Way Model Bake-Off")
    st.warning("This process may take 5-10 minutes, depending on the number of SKUs.")
    
    if st.button("Start Forecast Pipeline", type="primary"):
        with st.spinner("Running... This will take a while. Please wait."):
            try:
                # Use st.empty() to show progress updates
                progress_placeholder = st.empty()
                
                # We can't capture `tqdm` output, but we can wrap the call
                # and show log messages if we modify the script.
                # For now, just run main()
                
                start_time = time.time()
                
                # --- Call the main function from the imported script ---
                forecast_model.main()
                # ---
                
                end_time = time.time()
                
                st.success(f"Forecast pipeline completed successfully in {end_time - start_time:.2f} seconds.")
                st.balloons()
                st.info("You can now view all generated outputs in the 'View Results' tab.")
                # Clear caches to reload new data
                st.cache_data.clear()

            except Exception as e:
                st.error(f"An error occurred while running the forecast:")
                st.exception(e)

# --- Tab 3: View Results ---
with tab_results:
    st.header("Analyze Forecast Results")
    st.markdown("This tab shows the outputs generated by the forecast pipeline.")

    # Check if files exist
    if not os.path.exists(VALIDATION_RESULTS_CSV):
        st.info("No results found. Please run the forecast pipeline in the 'Run Forecast Pipeline' tab first.")
    else:
        # 1. Validation Scorecard
        st.subheader("1. Model Validation Scorecard")
        st.markdown("This table shows the RMSE (error) for all 5 competing models for each SKU. The `Best_Overall_Model` is the one with the lowest error.")
        df_validation = load_data(VALIDATION_RESULTS_CSV)
        if df_validation is not None:
            st.dataframe(df_validation.style.highlight_min(
                axis=1, 
                subset=['SARIMA_Uni_RMSE', 'ETS_Uni_RMSE', 'Prophet_Uni_RMSE', 'SARIMAX_Exog_RMSE', 'Prophet_Exog_RMSE'],
                color='lightgreen'
            ))
            
            st.download_button(
                label="Download Scorecard CSV",
                data=df_validation.to_csv(index=False).encode('utf-8'),
                file_name=VALIDATION_RESULTS_CSV,
                mime='text/csv',
            )
        else:
            st.error(f"Could not load {VALIDATION_RESULTS_CSV}")

        # 2. Validation Plots
        st.subheader("2. Validation Plot Viewer")
        if df_validation is not None:
            sku_list = df_validation['Material'].unique()
            selected_sku = st.selectbox("Select an SKU to view its validation plot:", sku_list)
            
            if selected_sku:
                plot_path = os.path.join(PLOT_DIR, f'validation_plot_{selected_sku}.png')
                image = load_image(plot_path)
                if image:
                    st.image(image, caption=f"Validation plot for {selected_sku}", use_container_width=True)
                    # Add download button for the image
                    with open(plot_path, "rb") as f:
                        st.download_button(
                            label=f"Download Plot for {selected_sku}",
                            data=f.read(),
                            file_name=os.path.basename(plot_path),
                            mime="image/png"
                        )
                else:
                    st.warning(f"Plot for {selected_sku} not found. (Expected at {plot_path})")
        else:
            st.info("Validation results not loaded, cannot display plots.")

        # 3. Final Forecast
        st.subheader("3. Final 6-Month Forecast (Units)")
        st.markdown("This is the raw output from the 'best' model for each SKU, showing the 6-month unit forecast.")
        df_forecast = load_data(FORECAST_CSV)
        if df_forecast is not None:
            st.dataframe(df_forecast)
            st.download_button(
                label="Download Forecast CSV",
                data=df_forecast.to_csv().encode('utf-8'), # Index is Material
                file_name=FORECAST_CSV,
                mime='text/csv',
            )
        else:
            st.error(f"Could not load {FORECAST_CSV}")

        # 4. Production Plan
        st.subheader("4. Actionable Production Plan")
        st.markdown("This plan combines the forecast with `Inventory_On_Hand` to calculate the `Net_Need` (how much to produce) and `Ending_Inv` for each month.")
        df_plan = load_data(PLAN_CSV)
        if df_plan is not None:
            st.dataframe(df_plan)
            st.download_button(
                label="Download Production Plan CSV",
                data=df_plan.to_csv(index=False).encode('utf-8'),
                file_name=PLAN_CSV,
                mime='text/csv',
            )
        else:
            st.error(f"Could not load {PLAN_CSV}")